services:
  postgres:
    image: postgres:15
    ports:
      - "5499:5432"
    environment:
      POSTGRES_DB: hms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  spring-boot-app:
    build: .
    image: hospital-mvc:1.0.0-SNAPSHOT
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hms
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SERVER_PORT: 8081
    depends_on:
      - postgres

volumes:
  postgres_data: